services:
  db:
    image: postgres:alpine
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fuzzy_catalog
  web:
    build:
      context: .
      dockerfile: ./Dockerfile

    # volumes:
    #   - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      PHX_HOST: localhost:4000
      DATABASE_URL: postgresql://postgres:postgres@db:5432/fuzzy_catalog
      SECRET_KEY_BASE: bN9RtuJXk/KUF6swIIUHNxHDNgLd9DvWC7N+vdEdsieYKvYPLckU2q/40deQVy4K
volumes:
  postgres_data:
